Repository liquibase/liquibase-opensearch-spring-boot-starter, pull requests merged in 2025-07, with the labels that each got.

#26 DAT-20361 GitHub Secrets Migration
  .github/workflows/dry-run-release.yml
Labels: sdou, skipReleaseNotes

#30 run integration tests in CI
  .github/workflows/test.yml
Labels: sdou

#18 add first implementation
  README.md
  pom.xml
  src/main/java/liquibase/ext/opensearch/integration/spring/LiquibaseOpenSearchAutoConfiguration.java
  src/main/java/liquibase/ext/opensearch/integration/spring/SpringLiquibaseOpenSearch.java
  src/main/java/liquibase/ext/opensearch/integration/spring/SpringLiquibaseOpenSearchProperties.java
  src/main/java/test/Dummy.java
  src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  src/test/java/liquibase/ext/opensearch/integration/spring/SpringLiquibaseOpenSearchDisabledIT.java
  src/test/java/liquibase/ext/opensearch/integration/spring/SpringLiquibaseOpenSearchIT.java
  src/test/java/liquibase/ext/opensearch/integration/spring/SpringTestApplication.java
  src/test/java/test/DummyTest.java
  src/test/resources/application.properties
  src/test/resources/liquibase.properties
  src/test/resources/liquibase/ext/changelog.httprequest.spring-variable.yaml
Labels: TypeEnhancement

#33 fix punctuation in README
  README.md
Labels: sdou

#32 fix repo URL in `pom.xml`
  pom.xml
Labels: sdou
